cache:
  key: "$CI_COMMIT_REF_NAME-cache" # one cache per branch
  paths:
    - build/

stages:
  - clean
  - configure
  - build
  - test
  - package

.linux:
  tags:
    - linux

.windows:
  tags:
    - windows

.osx:
  tags:
    - osx

# Clean
.clean:
  stage: clean
  script:
    - cmake -E remove_directory build
  when: manual

clean-linux:
  extends:
    - .clean
    - .linux

clean-windows:
  extends:
    - .clean
    - .windows

clean-osx:
  extends:
    - .clean
    - .osx

# Configure
.configure:
  stage: configure
  script:
    - cmake -E make_directory build
    - cd build
    - cmake $BUILD_ARCHITECTURE $ADDITIONAL_OPTIONS -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..

configure-linux:
  extends:
    - .configure
    - .linux

configure-windows:
  extends:
    - .configure
    - .windows
  variables:
    BUILD_ARCHITECTURE: -Ax64
    ADDITIONAL_OPTIONS: -DWINDOWS_BUILD_WIN32=ON

configure-osx:
  extends:
    - .configure
    - .osx
  variables:
    ADDITIONAL_OPTIONS: -DMACOSX_BUILD_BUNDLE=ON

# Build
.build:
  stage: build
  script:
    - cmake --build build --config Release

build-linux:
  extends:
    - .build
    - .linux
  needs:
    - configure-linux

build-windows:
  extends:
    - .build
    - .windows
  needs:
    - configure-windows

build-osx:
  extends:
    - .build
    - .osx
  needs:
    - configure-osx

# Test
.test:
  stage: test
  script:
    - cd build
    - ctest -C Release -j 8 --output-on-failure
  artifacts:
    when: on_failure
    paths:
      - build/Test*.png

test-linux:
  extends:
    - .test
    - .linux
  needs:
    - configure-linux
    - build-linux

test-windows:
  extends:
    - .test
    - .windows
  needs:
    - configure-windows
    - build-windows

test-osx:
  extends:
    - .test
    - .osx
  needs:
    - configure-osx
    - build-osx

# Package
.package:
  stage: package
  script:
    - cd build
    - cpack -C Release

package-linux:
  extends:
    - .package
    - .linux
  needs:
    - configure-linux
    - build-linux
    - test-linux
  artifacts:
    paths:
      - build/f3d-*.tar.gz
      - build/f3d-*.tar.xz

package-windows:
  extends:
    - .package
    - .windows
  needs:
    - configure-windows
    - build-windows
    - test-windows
  artifacts:
    paths:
      - build/f3d-*.zip
      - build/f3d-*.exe

package-osx:
  extends:
    - .package
    - .osx
  needs:
    - configure-osx
    - build-osx
    - test-osx
  artifacts:
    paths:
      - build/f3d-*.dmg
